- chicago/__init__.py
- chicago/bills.py
- chicago/events.py
- chicago/legistar.py
> All Chicago Scrapers

- chicago/bills.py
- chicago/legistar.py
The Chicago scraper failed locally for me (and is still running for 12+ hours, so I haven't seen it finish). @fgregg, feel free to ditch this PR if this is overlap with work you've done.
> Chicago: bugfixes

- chicago/__init__.py
- chicago/bills.py
- chicago/events.py
- chicago/legistar.py
- chicago/people.py
NOT ACTUALLY READY TO GO, want to run a bunch of stuff past @fgregg 
1) this was failing locally for me on the changes you made to the legistar scraper. I'll comment directly on that line. Can you check it and make sure my changes don't hurt anything?
2) I'm having trouble with duplicate events during the database import phase. In some cases it looked like event rescheduling notices, so I added some more possible rescheduling text, but it's also pulling things like this, which all seem to be the same event.
https://chicago.legistar.com/MeetingDetail.aspx?ID=184426&GUID=0FB72168-5E0C-4F42-B782-E79DCCC1B9B6&Options=info|
https://chicago.legistar.com/MeetingDetail.aspx?ID=190991&GUID=14BD8DD5-4C57-4A11-AA09-D124C9551DB0&Options=info| …
> plugging through database import issues

- miamidade/bills.py
Currently, the scraper for Miami-Dade County doesn't make reference to the original bills on miamidade.gov because the bill object doesn't list the source URL as coming from the web; this rectifies the issue.
> Add web source to Miami-Dade Bills; necessary for councilmatic

- chicago/bills.py
- nyc/bills.py
Add Repealed as a bill action to chicago and City Agency Report as a leg type to nyc
> Add a new action to chicago and a leg type to nyc

- lametro/people.py
@fgregg 
Could you look at this? It accounts for people, like Carrie Bowen, who are "non-voting members" on committees: https://metro.legistar.com/PersonDetail.aspx?ID=147630&GUID=E9CEE784-7AD0-4322-98B2-23D50EB800D8&Search=
(And sorry, my text editor created white space changes that I did not add...this only seems to happen with this repo. In any case, the relevant code changes are on lines 96-100.)
> Include non-voting memeber in committee roles

- README.md
The PR adds instructions for dealing with the misalignment between PyPI and master of ocd-django.
> Update readme with instructions to assign DJANGO_SETTINGS

- lametro/bills.py
LA Metro isn't that active, so the narrow time window was throwing a no-objects-returned ScrapeError. This PR resolves that issue by expanding the scrape window from three days to two weeks.
> Widen scrape window for LA Metro events

- nyc/bills.py
@fgregg - this PR resolves https://sentry.io/datamade/ocd-scrapers/issues/336893006/
I put "None" as the value, since I do not see any existing classifications that could make sense. Does that sound okay?
> Update ACTION_CLASSIFICATION dict

- lametro/events.py
Sometimes redirects to audio for LA Metro events do not contain the link to the desired audio resource in the `Location` header. This PRs skips those events for retrying later.
> Skip events for which we cannot retrieve existent audio file

- nyc/bills.py
Fixes https://sentry.io/datamade/scrapers-us-municipal/issues/408938398/
> Remove leading space in action classification dict

- lametro/events.py
This PR relates to [this issue for LA Metro](https://github.com/datamade/la-metro-councilmatic/issues/238). 
I placed the Guid within `extras`, since Pupa reserves the extras dict for [irregular fields](https://github.com/opencivicdata/pupa/blob/274cd0ddf9d550c5b20cd99d6d19720041d21222/ARCHITECTURE.md).
> Metro guid

- nyc/people.py
Organizations of the same name, from different jurisdictions, conflict with one another on person import [if an Organization object is not passed to `add_membership`](https://github.com/opencivicdata/pupa/blob/master/pupa/scrape/popolo.py#L112). This rectifies the situation for the NYC scraper.
Resolves https://sentry.io/datamade/scrapers-us-municipal/issues/411920264/
> Pass Organization obj when adding memberships

- chicago/bills.py
To mine eye, it looks like the duplicate actions have been removed from our original problem events:
* https://chicago.legistar.com/LegislationDetail.aspx?ID=3110438&GUID=53CF438E-7246-4785-B351-2417AFBE6C6B&Options=Advanced&Search=
* https://chicago.legistar.com/LegislationDetail.aspx?ID=3110435&GUID=5C6F4710-8B6F-487B-BCEF-BF8A56A3F030&Options=Advanced&Search=
Meanwhile, there's a new bill with duplicate actions [causing problems](https://sentry.io/datamade/scrapers-us-municipal/issues/325748109/):
* https://chicago.legistar.com/LegislationDetail.aspx?ID=1008361&GUID=612DD16C-B058-4C7B-AB5E-C78AE7CC7BAB
This PR removes the bills that have been fixed and adds the broken one.
> Add one problem bill to Chicago scraper, remove two

- chicago/people.py
There isn't always a photo for councilmen and women in Chicago Legistar (see: https://chicago.legistar.com/PersonDetail.aspx?ID=61032&GUID=C6D883F6-384D-4896-8EDB-522AE8247206&Search=). A photo is only added to the `web` dict by `python-legistar` [if there is a photo on the web page](https://github.com/opencivicdata/python-legistar-scraper/blob/master/legistar/people.py#L35-L38). Use `get` rather than assuming a photo will always be there.
Closes https://sentry.io/datamade/scrapers-us-municipal/issues/413541017/
> get Photo from web dict to avoid KeyError in Chicago scraper

- lametro/events.py
This PR adds the appropriate status options for events. Setting `status` to an empty string throws[ a pupa validation error](https://github.com/opencivicdata/pupa/blob/a76293c4c1b17374f05f30b2b981645365d828a7/pupa/scrape/base.py#L170). Here, we can set [`status` to "tentative,"](https://github.com/opencivicdata/pupa/blob/82b5d865fd6d984fb1b9960bef9bf64da0f6b9ce/pupa/scrape/schemas/event.py#L38), if the `EventAgendaStatusName` does not have a label of "Draft," or "Final," "Canceled."
> Add correct alternative status

- nyc/bills.py
There is apparently more than one way to [_sine_ a _die_](https://github.com/opencivicdata/scrapers-us-municipal/blob/b9aae1ae5257e261623cdb08b884afd62eeab7c5/nyc/bills.py#L432)!!
> Add new action class to NYC bill scraper

- nyc/bills.py
Related to https://github.com/opencivicdata/python-legistar-scraper/issues/59
Allows user to pass in `matter_id` to update a specific bill, rather than having to update all the bills in relevant time period.
> Fetch specified bill from NYC API

- chicago/people.py
The City Hall address contact type hard-coded into the scraper did not match the contact label in Legistar. 
In effect, this prevented us from scraping any City Hall addresses.
This PR fixes the key so City Hall addresses are recorded appropriately.
> Add correct key for City Hall address in Chicago people scraper

- nyc/bills.py
This PR adds "local_classification" to extras, since the[ `import_data` in django-councilmatic uses this value to create bill_types](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/management/commands/import_data.py#L952).
> Add extras

- nyc/bills.py
Some bills in the NYC API don't have a last-updated date, and so will never be scraped in our current setup. Update the bills scraper to call `self.matters` without a last-updated date when `window=0` so that all matters, including those that lack last-updated date, can be scraped.
> Scrape all NYC bills via window=0

- nyc/bills.py
https://www.youtube.com/watch?v=CTAud5O7Qqk
Closes https://sentry.io/datamade/scrapers-us-municipal/issues/417390870/
> Use float rather than int when checking window in NYC bills scraper

- nyc/people.py
In the people scraper, we add people to the `web_info` dict without formatting the name string, [(1)](https://github.com/opencivicdata/scrapers-us-municipal/blob/a5096da67dc94719c7ca2812c6fff8c7182c56a3/nyc/people.py#L28), [(2)](https://github.com/opencivicdata/scrapers-us-municipal/blob/a5096da67dc94719c7ca2812c6fff8c7182c56a3/nyc/people.py#L41-L48); however, we try to access them with a formatted name string, [(3)](https://github.com/opencivicdata/scrapers-us-municipal/blob/a5096da67dc94719c7ca2812c6fff8c7182c56a3/nyc/people.py#L53-L57), and moreover add them to the `members` dict (used later) with that formatted string, [(4)](https://github.com/opencivicdata/scrapers-us-municipal/blob/a5096da67dc94719c7ca2812c6fff8c7182c56a3/nyc/people.py#L117).
For the sake of simplicity, this PR …
> Only strip names at point of Person object creation in NYC people scraper

- chicago/bills.py
All problem bills in Chicago have been resolved! I retained the code for skipping the problem bills for posterity – does this seem right, or should we get rid of it?
> -1 problem bills

- nyc/bills.py
- nyc/people.py
The previous approach of only formatting names at the saving to the OCD API assumed that trailing spaces were consistent between the Legistar GUI and the Legistar API. As it turns out, this is not always the case, which means that we'd lose information, i.e., post, in the scrape where the spaces weren't consistent. This PR strips all names, everywhere in the people scraper.
FWIW, here's the impact on my local import after the changes:
```
import:
jurisdiction: 0 new 0 updated 1 noop
membership: 49 new 0 updated 3420 noop
organization: 0 new 0 updated 131 noop
person: 2 new 8 updated 184 noop
post: 0 new 0 updated 51 noop
```
> Always strip names in NYC people scraper

- chicago/events.py
They changed "Transcript" to "Captions", so let's follow suit (and resolve [this KeyError](https://sentry.io/datamade/scrapers-us-municipal/issues/476066019/events/14921912070/)).
Cached site:
Live site:
> Update Chicago scraper to reflect new table heading in event list

- lametro/events.py
legistar doesn't natively support multi-lingual support for events, so they are added a near-duplicates. we are going to scrape them as one event, and so must match them.
> match english and spanish events for la metro 

- lametro/events.py
I had to run a full scrape around a hundred times today to address #222. 
This makes changes that took  `pupa update import --fastmode lametro events` from 7 minutes to 30 seconds. (assuming cached data, for both).
This should not change the output of the scraper.
> Speed up the merging of english and spanish events, particularly for full scrapes

- lametro/events.py
This suppresses some matters to avoid unresolved ids. Relates to #222
> suppres some matters in agenda items for lametro

- lametro/events.py
This fixes a bug I introduced in #223 that prevented us from scraping unpaired events.
> unpaired events

- lametro/__init__.py
- lametro/bills.py
The old `sessions` method required dates to be updated in two places. This refactor allows for an update in one place (and adds the new session).
> Use legislative sessions defined on __init__ in Metro scraper

- lametro/bills.py
So, it seems like Metro calls the Board of Directors "Board of Directors – Regular Board Meeting" when it's listed as a sponsor in Legistar. `pupa` can't resolve this to the correct organization. This PR removes the board meeting suffix from "Board of Directors" when scraping matter sponsorships.
> Make Board of Directors Metro matter sponsor resolve-able to organization

- lametro/bills.py
This PR follows the pattern given in NYC, which enables parameters that can: (1) scrape all bills, and (2) scrape specific bills. (Thanks @hancush for doing the legwork on this one!)
> Enable matter_id specific scrapes and full bill scrapes

- lametro/people.py
@fgregg - I think it's more accurate to add `acting: true` to current memberships only (since we do not know the status of her post during previous legislative sessions).
> Add an extras field only to 'current' acting members

- lametro/people.py
This PR uses "Chief Executive Officer" as a role in Metro, since the Metro CEO is neither a "member" nor "non-voting member" of committees.
Related to https://github.com/datamade/la-metro-councilmatic/issues/351
> Treat CEO as a role in committees, as the scraper does with the Board

- lametro/bills.py
This PR adds `MatterRestrictViewViaWeb` to the extras field for Metro bills. It handles the very first portion of https://github.com/datamade/la-metro-councilmatic/issues/345
> Add MatterRestrictViewViaWeb to extras

- lametro/bills.py
This PR handles the first condition described here https://github.com/datamade/la-metro-councilmatic/issues/345#issuecomment-422949092.
> Skip bills with restricted view

- .gitignore
- lametro/bills.py
This PR enables Metro to scrape private bills and also marks which bills do and do not have a restricted view.
It works in cooperation with the changes in https://github.com/opencivicdata/python-legistar-scraper/pull/81.
> Add token to params

- lametro/bills.py
This PR adds a note to the `source_url` of private bills. This change helps facilitate import on the Councilmatic side.
> Add note to source_url

- lametro/bills.py
- tests/lametro/conftest.py
- tests/lametro/test_bills.py
This PR does the following:
1. toggles `scrape_restricted` to True – to enable scraping private bills
2. adds `start_date_private_scrape`, which tells the scraper to skip private bills introduced before '2016-07-01'
3. [clarifies the logic for identifying private bills](https://github.com/opencivicdata/scrapers-us-municipal/pull/262/files#diff-e3866abdbe598ba387e059bc654df79fR48)
The PR also initializes a tests repo! It includes a couple simple, parametrized unit tests for checking that the scraper correctly identifies public and private bills.
> Limit private scrape

- requirements.txt
- tests/lametro/test_bills.py
This PR mocks requests to Legistar, which (eventually) should facilitate automated testing via travis.
> Use requests_mock to mock requests to Legistar with empty JSON

- lametro/bills.py
Bill subjects [defaults to an empty list](https://github.com/opencivicdata/python-opencivicdata/blob/master/opencivicdata/legislative/models/bill.py#L35). Adding a dummy subject to restricted bills leads to that subject appearing as a facet in Councilmatic when those bills are made public. Since we don't need to add a value, and we aren't using this dummy subject anyplace else downstream, let's not add it.
> Don't add dummy subject to restricted bills

- lametro/events.py
- tests/lametro/conftest.py
- tests/lametro/test_events.py
This PR addresses https://github.com/datamade/la-metro-councilmatic/issues/337.
As the issue details, Legistar has – on at least one known occasion – duplicated the 'EventItemAgendaSequence'. This PR handles the problem by checking if an agenda has duplicate 'EventItemAgendaSequence', and if so, raising a ValueError with an instructive message to contact Metro. 
N.b., later on, we may implement a solution that flags problematic Events and, rather than raising an error, renders a message to Metro admin further downstream.
> Agenda sequence dedupe

- lametro/bills.py
This PR makes use of the optional `latest_version_value` arg in the newly devised `text` method: https://github.com/opencivicdata/python-legistar-scraper/pull/82/files
It relates to https://github.com/datamade/la-metro-councilmatic/issues/237
> Find matter_version_value and pass it into text

- nyc/bills.py
- nyc/events.py
- nyc/people.py
noticed that the canonical urls for legistar are not https.
> https for nyc legistar

- lametro/bills.py
This PR adds a key for "NO ACTION TAKEN" to the `ACTION_CLASSIFICATION` dict.
> Handle "NO ACTION TAKEN" history item in LA Metro scraper

- lametro/bills.py
This PR modifies `lametro/bills.py` to handle null VoteValueNames. This was throwing an error because that is a required field. 
After talking to LA Metro, we're inputting them as "present" which then is mapped to an OCD standard option.
> Adding exception handling for VoteValueName to lametro

- chicago/bills.py
- chicago/people.py
The Chicago scrapers have been failing to due to unexpected null values. This PR addresses that.
> Handle null vote options and end dates in the Chicago scrapers

- chicago/bills.py
Sometimes, Chicago logs absence in voice votes, e.g., http://webapi.legistar.com/v1/chicago/eventitems/359570/votes.
This PR updates the voice vote logic to accept skipping those votes.
> Accept skipping absent voice votes

- lametro/__init__.py
It looks like [Eric Garcetti is listed as "Vice Chair"](https://metro.legistar.com/PersonDetail.aspx?ID=144844&GUID=A840E600-58F9-43DC-8E71-C54334C73C25&Search=) and that is causing the scraper to break. We don't have a Vice Chair role set, just 1st Vice Chair and 2nd Vice Chair.
This adds in "Vice Chair" as a position until we learn whether it should resolve to a different position.
> LA Metro: adding in Vice Chair as a position

- lametro/events.py
We use the name, date, and time to pair English and Spanish events. Today, the time for an event pair did not match, so the scraper did not merge the events, resulting in an orphaned Spanish event that disappeared into the ether. We're still learning whether the times did not match in error or on purpose, but it would be good to know when our expectations are violated. This PR performs a defensive assertion that we've paired all Spanish events.
> Defensively assert that no Spanish events remain unpaired

- lametro/events.py
Per https://github.com/datamade/la-metro-councilmatic/issues/393#issuecomment-507776469, Spanish and English events will always occur at the same time. Therefore, the keys we use to match the events are sufficient if they contain the committee name and date of meeting. 
This PR removes the event time as a part of the `partner_key` and `key`.
> LA Metro: Removing time as a necessity for partnering English/Spanish events

- lametro/bills.py
Mapping `FAILED` to the correct action. Adding a comment about where those correct actions are located.
> LA Metro: adding FAILED as an action

- lametro/events.py
Sometimes if there is an issue getting the Spanish audio created, Metro has the Spanish Audio link
go to the English Audio.
Pupa does not allow the for duplicate media links, so we'll ignore the the second media link if it's
the same as the first media link.
Because of the way that the event['audio'] is created the first audio link is always English and the
second is always Spanish
> handle duplicate audio links

- nyc/events.py
NYC event imports were failing with this traceback:
```
Traceback (most recent call last):
File "/Users/hannah/.virtualenvs/scrapers-us-municipal/lib/python3.7/site-packages/django/db/models/query.py", line 486, in get_or_create
return self.get(**lookup), False
File "/Users/hannah/.virtualenvs/scrapers-us-municipal/lib/python3.7/site-packages/django/db/models/query.py", line 399, in get
self.model._meta.object_name
opencivicdata.legislative.models.event.EventLocation.DoesNotExist: EventLocation matching query does not exist.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/Users/hannah/.virtualenvs/scrapers-us-municipal/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
return self.cursor.execute(sql, …
```
> Add method to strip extra whitespace from NYC event locations

- lametro/events.py
This event had duplicated minutes because they appeared in the API on the detail page.
- http://webapi.legistar.com/v1/metro/events/1169
- https://metro.legistar.com/MeetingDetail.aspx?ID=493213&GUID=CDB198B6-DE4C-4EBB-88A6-946F93F07991&Options=info&Search=
The minutes url pointed to the same doc. This broke the councilmatic expectation that there were only one set of minutes, preventing the meeting from showing up.
https://sentry.io/organizations/datamade/issues/1316778912/?project=137567&referrer=slack
> only allow one set of mintues to be added

- lametro/people.py
Closes #295.
This PR makes a small change to import Metro's taxpayer oversight committees.
- Import people: `pupa update lametro people --rpm=0`
- Import events: `pupa update lametro events --rpm=0`
- Shell into your database, e.g., `psql opencivicdata`. (May vary, if your database is called something else or if you need to set additional connection parameters.)
- Confirm that there are oversight committees in your organization table: `select id, name from opencivicdata_organization where jurisdiction_id = 'ocd-jurisdiction/country:us/state:ca/county:los_angeles/transit_authority';`
- Grab the ID of the Measure M Taxpayer Oversight Committee and substitute it into the following query to confirm events have been imported: `select e.id, e.name, e.start_date from opencivicdata_event as e …
> Import oversight committees

- lametro/events.py
Connects https://github.com/datamade/la-metro-councilmatic/issues/393 and https://github.com/opencivicdata/python-legistar-scraper/pull/100.
The Metro scraper pairs English and Spanish Legistar events. When we are conducting a partial scrape, it's possible that one language event will be included, but not the other. We have logic to handle this case, however it relies on `since_datetime` being passed as a keyword argument to check whether a scrape is partial. This check did not work because [we pass this value as a positional argument in the `python-legistar` library](https://github.com/opencivicdata/python-legistar-scraper/blob/371cea70980aced81a31b2dcce4284bdc1fc2d28/legistar/events.py#L200), hence the scraper never recognized partial scrapes and accordingly never looked for missing …
> Fix English and Spanish event pairing in Metro scraper

- lametro/events.py
- tests/lametro/conftest.py
- tests/lametro/test_events.py
This PR completes the work started in #284, by removing the time constraint from `is_partner` and `partner_search_string` when pairing English and Spanish Metro events. It also adds a clarifying comment to an inline assertion and a test for the `_merge_events` method. It closes #308.
> Definitively remove event time constraint from Metro event pairing

- lametro/events.py
- lametro/people.py
This PR makes changes to the LA Metro scraper to try to handle in the data layer issues that had been handled in Metro's Councilmatic view code. Most significantly:
1. trying to find at attach minutes to meetings
2. attaching family name to person (which we'll use for sorting)
3. agenda_numbers to extras for sorting
> Upgrades to the LA Metro scraper

- lametro/events.py
Starting next week, LA Metro will be inputting service council events into Legistar. These are distinct from the governing board/committees, so they don't wish to include them in their instance of Councilmatic. This PR adds a line to the event scrape to omit service council meetings.
Connects https://github.com/datamade/la-metro-councilmatic/issues/606
> Metro: Don't scrape service council events

- lametro/people.py
This PR patches #320.
- Run the person scrape: `pupa update lametro people --rpm=0`
- Confirm the scrape completes successfully.
- Shell into your OCD database, and confirm the Metro board's given and family names match their display name: `select name, given_name, family_name from opencivicdata_person;`
> Grab given and family name from correct object

- lametro/bills.py
This PR strips leading and trailing whitespace from attachment links, as they cause validation and thus the scrape to fail: 
```
ScrapeValueError: validation of Bill cb909502-c6a4-11ea-b792-0242ac110002 failed: 
'http://libraryarchives.metro.net/DB_Attachments/151106_Attachment_A_Addendum_FEIR_with_Appendices.pdf ' is not a 'uri'
Failed validating 'format' in schema['properties']['documents']['items']['properties']['links']['items']['properties']['url']:
{'format': 'uri', 'type': 'string'}
On instance['documents'][0]['links'][0]['url']:
'http://libraryarchives.metro.net/DB_Attachments/151106_Attachment_A_Addendum_FEIR_with_Appendices.pdf '
File "bin/pupa", line 8, in <module>
sys.exit(main())
File "pupa/cli/__main__.py", line 68, in main
subcommands[args.subcommand].handle(args, other) …
```
> Strip leading and trailing whitespace from links

- lametro/events.py
Similarly to #319, this PR adds logic to skip service council public hearings. I went this route, rather than skipping any meeting of a body containing "Service Council" because I figured the specificity would be more future-proof. 
Handles https://github.com/datamade/la-metro-councilmatic/issues/634.
> Metro: Skip service council public hearings

- lametro/events.py
- lametro/people.py
Surprise! Data entry isn't always consistent. This PR adds an extra search to grab the IDs of all bodies of the Service Council (70) or Service Council Public Hearing (75) body type, and skips any meetings of those bodies, rather than trying to pattern match the name.
Handles https://github.com/datamade/la-metro-councilmatic/issues/606, https://github.com/datamade/la-metro-councilmatic/issues/634.
> Metro: Use body type to skip service council and service council public hearing events

- lametro/people.py
Metro now has first and second vice chairs. This PR adds them to the scraper, so they aren't overwritten as "Member".
> Add new board office roles to scraper

- lametro/bills.py
This PR adds Logic to the Metro bill scraper to skip attachments if `MatterAttachmentShowOnInternetPage` is False. It would probably be ideal to handle this similarly to the way we do bills, i.e., scrape a record of the attachment but don't scrape any metadata or show in the user interface, but there is an immediate need to suppress an attachment on the live site, and this is the fastest way to achieve it, for now.
- Scrape a bill with a suppressed attachment and confirm that the output does not have any related documents: `pupa update --scrape lametro bills matter_ids=7212`
> LA Metro: Skip attachments that are not visible in the web interface

- lametro/events.py
this gives same behavior as setting a windows to '0' for event scraper.
not having this caused us to miss events when we turned of nightly full scrapes
> do full scrape if window is '0'

- lametro/people.py
Metro wants to hold committee memberships for Holly Mitchell until they are announced. This PR adds logic to skip committee memberships for an arbitrary list of people.
- Run `pupa update --scrape lametro people --rpm=0` and confirm that you see two log messages indicating Holly Mitchell's committee memberships are being skipped.
- Grep the `_data/` directory and confirm Mitchell herself, as well as her board membership, has been scraped.
> Skip committee memberships for pre-determined list of people

- lametro/people.py
This PR adds information about Tim Sandoval's post to the `VOTING_POSTS` object. Connects https://github.com/datamade/la-metro-councilmatic/issues/693.
> Metro: Add Tim Sandoval

- lametro/bills.py
This PR overrides the `matters()` method of the Metro bills scraper as described in the PR title. This logic is similar to the default event scrape logic, and also mirrors our logic for refreshing the document cache (https://github.com/datamade/django-councilmatic/pull/267). 
I made this change because Metro often updates board reports on upcoming agendas, but those updates do not toggle the corresponding updated at flag on the matter in the Legistar API, so the changes don't appear until the overnight bill scrape.
The number of extra calls is equal to `1 (call to retrieve windowed events) + number of events in the window (calls to retrieve agendas) + number of unseen matters (calls to retrieve the matters)`. Our regular windowed event scrapes (`window=0.05` and `window=1`) return ~20 …
> Metro: Scrape matters updated within a window, as well as matters related to events updated within a window

- lametro/bills.py
This reverts commit 5d29814c1f184f3c1decaae03aef459fdceab13c, reversing
changes made to bc5b2ef49eda9596946f438a6f3755656c2957c2.
I'm performing this revert because I'm putting this down until next week, and I don't want these changes on master in case a change needs to be made during support night.
> Undo changes to Metro bill scraping

- Dockerfile
- README.md
- docker-compose.yml
- docker-entrypoint.sh
See title. I made these changes so scrapers can run with only a local installation of Docker and Docker Compose (i.e., users need not manage a local installation of Postgis). 
Closes #339, connects https://github.com/datamade/la-metro-councilmatic/issues/687.
I used this setup to test the changes to `pupa` in https://github.com/opencivicdata/pupa/pull/336:
- Mount your local pupa directory as a volume into the `scrapers` service:
```yml
volumes:
- .:/src
- /abs/path/to/pupa:/pupa
```
- Spin up a scraper container and install the local version of pupa:
```bash
docker-compose run --rm --name scrapers scrapers /bin/bash
pip install -e pupa
```
- In a separate terminal window, execute a person scrape against the running scraper container:
```bash
docker exec scrapers pupa update lametro …
```
> Update Dockerfile, add Docker Compose setup

- lametro/bills.py
This reverts commit 92b11a1063cfaa75d7aa39bb93a247001242b1ac, re-applying changes from https://github.com/opencivicdata/scrapers-us-municipal/pull/344. Will merge when I'm ready to test these changes. Sorry for the snafus on master.
> Re-apply changes from scrapers-us-municipal/pull/344

- lametro/bills.py
Connects https://github.com/datamade/la-metro-councilmatic/issues/739.
- Run a bill scrape and confirm nothing breaks: `docker-compose run --rm scrapers pupa update lametro bills window=7 --rpm=0`
> Metro: Suppress unsent board correspondence

- lametro/events.py
This PR handles the case where there is more than one file approving minutes of a particular meeting. This is a stopgap to unbreak event scrapes while I work with Metro to determine the right thing to do in this instance. 
The breaking scenario is that minutes for a particular meeting were scheduled to be approved, but the approval was carried over to the next meeting. Then, a second file for the approval was created, rather than reusing the existing file. Interestingly, this file was withdrawn, so neither file actually represents the approval of minutes. 
As I said, I'm working with Metro to determine what to do in this case, but this only affects one event, and I don't think the scrapes should stay broken in the interim.
_Done locally._
- Run a full event scrape and confirm it finishes …
> Metro: Skip minutes inference if there is more than one minutes file

- lametro/events.py
See title. This fixes the event scrapes that have been failing all week. If there is more than one minutes attachment, it seems like we might be able to get the attachment containing the date of the event at hand, but I want to gather a few more examples before I commit to that strategy.
N.b., I have run the event scrape locally and confirmed that it completes successfully.
> METRO: Add more events with more than one minutes file

- lametro/events.py
This PR adds another handled case to multiple attachments to minutes matters, and, if there is more than one attachment moving forward, tries to grab the one with "minutes" in its title. 
Per Metro, the naming convention isn't guaranteed to be specific, but looking for "minutes" is a good starting point https://github.com/datamade/la-metro-councilmatic/issues/742#issuecomment-1048278789.
_Already done_
- Run a full event scrape and confirm it succeeds.
> Add another handled case, flexible logic for more than one attachment to minutes matter

- lametro/__init__.py
This PR adds in a new post for the Interim District 7 Director for LA Metro.
Handles #361 
* Run the people scraper with `docker-compose run --rm scrapers pupa update lametro people`
* Verify that all members are successfully loaded into the db
> Add District 7 interim post

- lametro/events.py
See title.
* Run the scraper (I used `docker-compose run --rm scrapers pupa update lametro events window=75 --rpm=0`) and verify that it doesn't raise any errors
> Handle another event with more than one minutes file

- lametro/events.py
This PR modifies the behavior of LA Metro scrapes to log `UnmatchedEventError`s and continue scraping rather than failing.
I tested by manually adding lines to raise an `UnmatchedEventError` in both `LametroEventScraper.api_events()` and `LametroEventScraper._merge_events()`.
> Catch UnmatchedEventErrors in lametro scrapes

- lametro/events.py
This PR changes the LA Metro scraper's behavior to log when events have multiple minutes files instead of raising an exception.
> Log multiple minutes errors in LA metro scraper

- lametro/bills.py
See title. The "MatterFile" property of temporary bills in Metro's Legistar instance begin with "TMP."
> Skip temporary bills for LA Metro

- lametro/bills.py
See title. This PR ensures we check that a bill is available _before_ trying to determine whether it's temporary.
> Fix temporary bill check logic

- lametro/people.py
See title.
This is necessary to prevent duplicate people from being created if a suffix is added later.
Connects https://github.com/datamade/la-metro-councilmatic/issues/920
> Metro: Remove (Interim) suffix from person name

- .github/workflows/main.yml
- docker-compose.yml
- lametro/bills.py
- requirements.txt
- tests/docker-compose.yml
- tests/lametro/conftest.py
- tests/lametro/test_bills.py
- tests/lametro/test_events.py
This PR adds logic to handle unnamed board correspondences, as outlined in [this LA Metro councilmatic issue](https://github.com/datamade/la-metro-councilmatic/issues/904). 
This PR also resurrects scraper tests. I've included a few updates to existing tests to get them passing and added a new one to test this board correspondence logic.
> Handle unnamed board correspondences
