opencivicdata/scrapers-us-municipal

chicago/bills.py
chicago/events.py
chicago/legistar.py

Fix time formatting error in events.

have date formatting happen downstream

---

chicago/__init__.py

I hope this will fix it, but this takes too long to run to check locally. @fgregg if this looks OK to you, we can pull it in and give it a try in production?

chicago legislative sessions maybe fixed

---

miamidade/__init__.py
miamidade/bills.py
miamidade/events.py
miamidade/people.py
miamidade/votes.py

this has been sitting around for a while, fixed it for location_name pupa change and figured why not get it running? it works.

Miami dade

---

chicago/bills.py
chicago/events.py

Some agenda items have a blank record #.

some agenda items don't have record numbers, scrape ALL the leg

---

chicago/events.py

We can now capture all the hearings. Everything runs locally.

add descriptions to events close #30

---

ferguson/__init__.py
ferguson/people.py

@paultag, could you look over this at some point and give me pointers? Huge thanks! This was a fun way to learn about OCD and Pupa.

Ferguson: Initial commit

---

nyc/__init__.py
nyc/events.py

This adds events scraper for nyc. Depends upon merging and deploying https://github.com/opencivicdata/python-legistar-scraper/pull/12

NYC events

---

nyc/__init__.py
nyc/bills.py
nyc/people.py

- Correct sessions
- Subcommittees are children of their correct committee
- Noncommittees are ommitted
- Sponsors are added
- Attachments are added
- Action classifications
- Bill classifications

Many fixes

---

nyc/bills.py

This adds the local classification to nyc bills, fixes attachment types, and adds related_entities to bill actions.

Add local classification and related entities

---

nyc/bills.py

Hi @rshorey, this is running now. Any chance you can kick this off today?

add action classification

---

chicago/__init__.py
chicago/bills.py
chicago/people.py

Bills use legistar base, Resolves ids

---

chicago/events.py

chicago events uses legistar package

---

chicago/bills.py
nyc/bills.py

Any chance I can get this merged? @fgregg Is not around this week and I just noticed that the pupa models were updated. Thanks!

Update local scrapers to use newer pupa models

---

chicago/bills.py
nyc/bills.py
requirements.txt

Making a few small changes to scrapers to synch up with 5.2.
@evz there's a pupa 5.2 migration we need to run on the server. When that is good to go, I'll merge.

synching up with pupa 5.2

---

miamidade/__init__.py
miamidade/people.py

This is a bit out of my head these days so I'm having trouble with my local database and can't confirm this resolves the post assignment issue, but I modelled it off the newer st louis one, so hopefully it does. @fgregg, do you have things set up such that you could easily check it locally? If not, it'll be quite some time before I get to it, unfortunately.

attempt to fix miami-dade posts problem

---

miamidade/people.py

Addresses issue #114 (seen on our local repo as https://github.com/Code-for-Miami/mia-councilmatic/issues/30)

Adds executive primary orgs for MDC, fixes #114

---

miamidade/__init__.py
miamidade/people.py

Updated pull request to reflect Forest's comments about `init.py`

Separate executive branches to own organizations, references #114

---

lametro/events.py

@fgregg I made changes to retrieve the audio link.

Add backslash to url and send HEAD request for audio link

---

chicago/__init__.py
chicago/events.py

Fix indentation problem in events scraper

---

nyc/bills.py

Per @reginafcompton, this change exists on our server (thx @evz) but never made its way into the repo, so adding it for tidiness & to avoid later confusion!

Only add NYC bill title if not null

---

chicago/bills.py
lametro/bills.py

@fgregg how does this look? (I do not see a place to add an else clause here, as you previously suggested: https://github.com/opencivicdata/python-legistar-scraper/pull/28#pullrequestreview-43285771)

Add try-except block for legislation_detail_url

---

nyc/bills.py

Resolves https://sentry.io/datamade/ocd-scrapers/issues/326031323/

Resolve maternity to excused in VOTE_OPTIONS

---

nyc/bills.py

Resolves https://sentry.io/datamade/scrapers-us-municipal/issues/336893006/

Add another action classification

---

lametro/bills.py

The newly added code in this PR iterates over matter relations (should they exist) and creates related bills. It assumes that each related bill is a "companion" - however, that may require further conversation. 
Related to [this issue](https://github.com/datamade/la-metro-councilmatic/issues/158) on Metro Councilmatic.

Add FOR loop for finding related bills

---

nyc/bills.py

This PR resolves [this issue](https://sentry.io/datamade/scrapers-us-municipal/issues/336893006/).

Add new actions to ACTION_CLASSIFICATION

---

lametro/bills.py

This PR resolves[ this issue](https://sentry.io/datamade/scrapers-us-municipal/issues/369319508/).

Set description to none if it contains 'do not use'

---

nyc/bills.py

Resolves https://sentry.io/datamade/scrapers-us-municipal/issues/336893006/

Add missing action class to dict

---

chicago/bills.py

Addresses https://sentry.io/datamade/scrapers-us-municipal/issues/415250019/

Add a problem bill, remove a problem bill

---

lametro/__init__.py
lametro/people.py

This PR relates to this Councilmatic issue: https://github.com/datamade/la-metro-councilmatic/issues/261
It scrapes the web to get accurate source URLs for the committees.

Scrape the web to get organization URLs

---

nyc/bills.py

Fixes https://sentry.io/datamade/scrapers-us-municipal/issues/465742287/

Add comment with options + another bill type

---

lametro/events.py

See inline comment for explanation.

Handle empty location for LA Metro

---

lametro/events.py

Using a similar pattern to audio, add the Spanish event GUID and detail URL to the API.

Add Spanish event GUID and detail URL to merged event

---

st_louis/bills.py

I believe this should close out issue #96

Fix bill STL scraper

---

ferguson/people.py

Fixes changes to the html structure for scraping person data for Ferguson.

Fix ferguson people scrapper

---

lametro/people.py

This PR adds a new board member, per this request: https://github.com/datamade/la-metro-councilmatic/issues/327

Replace Carrie Bowen with Shirley Choate

---

lametro/__init__.py
lametro/people.py

This PR handles part of https://github.com/datamade/la-metro-councilmatic/issues/327

Add new post with full title for non-voting member

---

.gitignore
sacramento/__init__.py
sacramento/bills.py
sacramento/events.py
sacramento/people.py
sacramento/vote_events.py

I'm building off of work from a previous member at Code4Sac. I want to get some data in for Sacramento so that we can power a local Councilmatic application.
Previously tried this PR on python-legistar-scraper.  @fgregg pointed me to this repo.  See the PR for more details: https://github.com/opencivicdata/python-legistar-scraper/pull/71.

Adding Sacramento city and populating people.py

---

lametro/people.py

@fgregg - I also need to show information about "acting" members in the Board of Directors.

Add info about acting membership to Board of Directors

---

lametro/__init__.py
lametro/people.py

Related to https://github.com/datamade/la-metro-councilmatic/issues/363
N.B. the post for the District 7 director is newly worded, per a request from LA Metro. It seems like we should assign Shirley Choate the newly worded post, too, rather than leaving her post as it is. (That's what I've done here.) @fgregg - could you advise?

Add John Bulinkski

---

lametro/__init__.py

This revision adds more information about the District 7 director, per a request from Metro. 
I plan to do manual database intervention, as needed, e.g., removing the old post and resultant duplicate memberships.

Revise post for district 7 director per request from Metro

---

lametro/bills.py

This PR responds to the issue raised here: https://github.com/datamade/la-metro-councilmatic/issues/401

Do not scrape private Metro bills

---

lametro/bills.py

Responds to https://sentry.io/organizations/datamade/issues/903306875/?project=56420&referrer=webhooks_plugin&statsPeriod=14d

Add bill type

---

lametro/bills.py

Addresses https://sentry.io/organizations/datamade/issues/903532164/?project=56420&referrer=webhooks_plugin&statsPeriod=14d

Skip bill with duplicate

---

lametro/events.py
tests/lametro/conftest.py
tests/lametro/test_bills.py
tests/lametro/test_events.py

This PR addresses https://github.com/datamade/la-metro-councilmatic/issues/414

Correctly classify events with Final status, and add test for events

---

lametro/bills.py
tests/lametro/conftest.py

This PR addresses https://github.com/datamade/la-metro-councilmatic/issues/387

Add another rule for restricting bills

---

lametro/events.py

In the quest to squash all 104s, this is the current challenge. Depends on https://github.com/opencivicdata/python-legistar-scraper/pull/88

get on that good retry patterns for checking to see if a legistar web url is valide

---

lametro/bills.py

Handles Sheila Kuehl's vote here: https://webapi.legistar.com/v1/metro/eventitems/14250/votes

Map 'conflict' vote to 'abstain'

---

chicago/people.py

This should resolve the "20th Ward Vacancy" errors we have been getting.

better check for skipping vanancies

---

chicago/__init__.py
chicago/bills.py
chicago/people.py

Depends on #277 
This PR adds the new 2019 session to Chicago scrapers.

2019 chicago session

---

lametro/__init__.py

This PR adds in the 2019-2020 legislative session, as meetings and agendas for that period are now being uploaded.

Adding the 2019 legislative session to lametro

---

chicago/bills.py

couple of issues arising from big chicago scrape

problems arising from big chicago scrape

---

chicago/events.py
lametro/events.py
nyc/events.py

This PR takes advantage of the simplified API event and depends on this python-legistar PR: https://github.com/opencivicdata/python-legistar-scraper/pull/93
- Clone the python-legistar repo
- checkout the change_events_scraping branch
- from the scrapers virtual env, `pip install -e .` this local python-legistar
```bash
pupa update lametro events
pupa update chicago events
pupa update nyc events
```

Legistar simplified events

---

lametro/events.py

revert last commit

---

lametro/events.py

This PR scrapes adds eComment links, if they're available, to Metro events.

Scrape eComment links

---

lametro/bills.py

See description. Resolves https://sentry.io/organizations/datamade/issues/1574010397/?project=56420.

Add 'Board Correspondence' to BILL_TYPES

---

lametro/__init__.py

This PR adds a new year for the new Metro legislative session.

New year, new legislative session

---

lametro/people.py

See title. Connects https://github.com/datamade/la-metro-councilmatic/issues/676.

Add Tony Tavares to non-voting members

---

lametro/people.py

See title. Connects https://github.com/datamade/la-metro-councilmatic/pull/685/

Metro: Add Holly Mitchell

---

lametro/people.py

This PR adds Fernando Dutra's information to the `VOTING_POSTS` object. Connects [datamade/la-metro-councilmatic/#707](https://github.com/datamade/la-metro-councilmatic/issues/707)

Scrape Fernando Dutra

---

lametro/people.py

This PR removes Holly Mitchell from PENDING_COMMITTEE_MEMBERS.
Addresses [lametro-councilmatic/issues/687](https://github.com/datamade/la-metro-councilmatic/issues/687)

Scrape holly mitchell

---

lametro/bills.py

Add NOT DISCUSSED action classification

---

lametro/people.py

This PR replaces non-voting LA Metro board member Tony Tavares with Gloria Roberts following Roberts' appointment as Interim District 7 Caltrans Director.

Add Gloria Roberts

---

docker-compose.yml

This PR undoes a change to the postgres image used by Docker.

Fix postgres image

---

lametro/people.py

Update LA Mayor to Karen Bass
